### PR TITLE
Risk Outcome Detail Component

### PR DESCRIPTION
**Pull request by ASTribble**
Added RiskOutcomeDetail component.
Props need to be passed in from parent.

### CODE REVIEW

**Comment by ASTribble** [comment]
As I'm working on the parent component, it might make more sense to pass a single year as a prop and split those values off that year.

**Comment by ASTribble** [comment]
After a second-second thought, I think this initial way is the better one.

**Comment by vampaynani** [comment]
I'm with you, it work as it is and at the end if you want to pass a single year as a prop you could do:
```
<RiskOutcomeDetail {...year} />
```

**Comment by ASTribble** [comment]
Cool.

**Pull request merged**
