### PR TITLE
Market outcome detail#353

### PR DESCRIPTION
**Pull request by ASTribble**
Added Market Outcome Detail Component.
It takes a deeply nested object from the parent, which can maybe be broken down  as we solidify what that information will actually look like in the state.

### CODE REVIEW

**Comment by ASTribble** [comment]
There were a few conflicts with what was showing on the dashboard.  I fixed them.

**Comment by ASTribble** [comment]
I left the object I used to test MarketOutcomeDetail in the mapStateToProps on the dashboard because it is so particular.  I have it in the component file itself if you feel like it should come off the dashboard.

**Review by samuelgould — CHANGES_REQUESTED** [review]
BE will have the risk collection in the following format: [{year: 1, risk: low, gain: 1.2}, ... , {year: 1, risk: mattress, gain: 0}], so the start value will have to be taken from the state as previousFund value and end should be dynamically calculated based on the gain.

**Comment by ASTribble** [comment]
Ok.  I think I understand, but I will check in with you about it and then re-work this component.

I'm going to close this pull request..

**Pull request closed without merging**
